name: strapi_dio_getx
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  get: ^4.7.2
  get_storage: ^2.1.1
  path_provider: ^2.0.15
  flutter_easyloading: ^3.0.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  flutter_image_compress: ^2.4.0
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.1
  table_calendar: ^3.0.9
  carousel_slider: ^5.0.0
  showcaseview: ^4.0.1
  animations: ^2.0.7
  device_preview: ^1.1.0
  animate_do: ^4.2.0
  dots_indicator: ^4.0.1
  card_swiper: ^3.0.1
  like_button: ^2.0.5
  flutter_staggered_animations: ^1.1.1
  flutter_slidable: ^4.0.0
  simple_animations: ^5.1.0
  image_stack: ^2.1.1
  flutter_rating_bar: ^4.0.1  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

flutter_native_splash:
  image: assets/images/logo_white.png
  color: "6759FF"
  color_dark: "#121212"
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
